---
- name: Get scopes
  uri:
    url: "{{mds_server_url}}/security/1.0/registry/clusters"
    method: GET
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force_basic_auth: true
    headers:
      Authorization: "{{ authorization_header }}"
    body_format: json
  register: clusters_list
  check_mode: false

- name: Get List Of Scopes
  set_fact:
    scopes_list: '{{ scopes_list | d([]) +  [item.clusterName] }}'
  loop: "{{ clusters_list.json }}"

- debug:
    msg: "{{scopes_list}}"
    verbosity: 3

- name: Failure if no scopes found
  fail:
    msg: "No scopes found - make sure your clusters are registered in the Cluster Registry"
  when: scopes_list|length == 0
