---
- name: Connectors management
  gather_facts: false
  hosts: "{{ run_host|default('localhost') }}"
  environment: "{{proxy_env}}"

  tasks:
    - name: Set Variables
      import_role:
        name: common

    - name: Process Connectors
      import_role:
        name: connectors
