---
# build a configuration structure from current state of rolebindings in the cluster
- set_fact:
    connectors_current: []

- name: Get All Connectors
  uri:
    url: "{{connectors_server_url}}/connectors"
    method: GET
    validate_certs: false
    force_basic_auth: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force: true
    headers:
      Authorization: "{{ authorization_header }}"
  register: connectors_list_tmp
  check_mode: false

- name: Process List Of Connectors
  include_tasks: tasks/connectors_dump_tasks.yml
  loop: "{{ connectors_list_tmp.json }}"
  when: connectors_list_tmp.json | d([]) | length > 0
  loop_control:
    loop_var: connector_item

- debug:
    var: connectors_current
    verbosity: 3
