---
- name: Get Connectors Configs
  uri:
    url: "{{connectors_server_url}}/connectors/{{connector_item}}/config"
    method: GET
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force_basic_auth: true
    headers:
      Authorization: "{{ authorization_header }}"
    body_format: json
    status_code: 200
  register: connector_config_temp
  check_mode: false

- name: Cleanup
  set_fact:
    connectors_current: '{{ connectors_current + [connector_config_temp.json] }}'
