---
- name: Add/Update Connectors
  uri:
    url: "{{connectors_server_url}}/connectors/{{item.name}}/config"
    method: "{{ http_method }}"
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force_basic_auth: true
    force: true
    status_code: "{{ http_status_code }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: application/json
    body: "{{ item }}"
    body_format: json
  register: result
  changed_when: result.status == http_status_code
  loop: "{{ connectors_op_list }}"
  when: http_method == "PUT"

- name: Delete Connectors
  uri:
    url: "{{connectors_server_url}}/connectors/{{ item }}"
    method: "{{ http_method }}"
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force_basic_auth: true
    force: true
    status_code: "{{ http_status_code }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: application/json
  register: result
  changed_when: result.status == http_status_code
  loop: "{{ connectors_op_list }}"
  when: http_method == "DELETE"
