---
# Low level topic operations - using Confluent Server v3 API
# create topic expects collection to topic configs, returns success for already existing topics
- name: Create topics
  uri:
    url: "{{rest_server_url}}{{url_cluster_prefix}}/v3/clusters/{{cluster_id}}/topics"
    method: POST
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    force_basic_auth: true
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: application/json
    body_format: json
    body: "{{item}}"
    return_content: true
  register: result
  failed_when: result.status != 201
  changed_when: result.status == 201
  loop: "{{topics_in |flatten(levels=1)}}"
