---
# Get cluster_id v1 API
- name: Get cluster_id
  uri:
    url: "{{rest_server_url}}{{url_cluster_prefix}}/v3/clusters"
    method: GET
    validate_certs: false
    force_basic_auth: true
    headers:
      Authorization: "{{ authorization_header }}"
    status_code: 200
    return_content: true
  register: result
  check_mode: false

- set_fact:
    cluster_id: "{{result.content | from_json | json_query('data[0].cluster_id')}}"
  check_mode: false
