---
# Get cluster_id v1 API
- name: Get cluster_id
  uri:
    url: "{{rest_server_url}}{{url_cluster_prefix}}/v3/clusters"
    method: GET
    validate_certs: true
    force_basic_auth: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    headers:
      Authorization: "{{ authorization_header }}"
    status_code: 200
    return_content: true
  register: result
  check_mode: false

- set_fact:
    cluster_id: "{{result.content | from_json | json_query('data[0].cluster_id')}}"
  check_mode: false
