---
- set_fact:
    combine_list: []
    acl_current_pk: []
    acl_desired_pk: []

- name: Flatten Desired ZACLs Patterns
  include_tasks: roles/common/tasks/_helper.yml
  loop: "{{ acls }}"
  loop_control:
    loop_var: item_patterns
  vars:
    mylist: "{{ item_patterns.patterns }}"
    myitem: "{{ { 'principal': item_patterns.principal } }}"

- set_fact:
    acl_pattern: "{{ combine_list }}"
    combine_list: []

- name: Flatten Desired ZACLs Entries
  include_tasks: roles/common/tasks/_helper.yml
  loop: "{{ acl_pattern }}"
  loop_control:
    loop_var: item_entries
  vars:
    mylist: "{{ item_entries.entries }}"
    myitem: '{{ { "principal": item_entries.principal, "pattern_type": item_entries.pattern_type, "resource_name" : item_entries.resource_name,
        "resource_type" : item_entries.resource_type } }}'

- set_fact:
    acl_desired: "{{ combine_list }}"

- debug:
    var: acl_list
    verbosity: 3

- debug:
    var: acl_desired
    verbosity: 3

- name: Add PKs current
  set_fact:
    acl_current_pk:
      '{{ acl_current_pk + [ item| combine({"tmppk": item.principal+item.pattern_type+item.resource_type+
        item.resource_name+item.host+item.operation+item.permission})] }}'
  loop: "{{ acl_list }}"

- name: Add PKs desired
  set_fact:
    acl_desired_pk:
      '{{ acl_desired_pk + [ item| combine({"tmppk": item.principal+item.pattern_type+item.resource_type+
      item.resource_name+item.host+item.operation+item.permission})] }}'
  loop: "{{ acl_desired }}"

- name: To Add
  set_fact:
    acl_to_add: '{{acl_to_add|d([]) + [item] }}'
  loop: "{{ acl_desired_pk }}"
  when:
    - item.tmppk in acl_to_add_name
  vars:
    acl_to_add_name: "{{acl_desired_pk | map(attribute='tmppk') | difference(acl_current_pk | map(attribute='tmppk') )}}"

- name: To Remove
  set_fact:
    acl_to_delete: '{{acl_to_delete + [item] }}'
  loop: "{{acl_current_pk }}"
  when:
    - item.tmppk in acl_to_delete_name
  vars:
    acl_to_delete_name: "{{acl_current_pk | map(attribute='tmppk') | difference(acl_desired_pk | map(attribute='tmppk') )}}"

- debug:
    var: acl_to_add
    verbosity: 2
- debug:
    var: acl_to_delete
    verbosity: 2
